// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riwiomlcrozbycrddyqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpd2lvbWxjcm96YnljcmRkeXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODU3NjIsImV4cCI6MjA2MDQ2MTc2Mn0.VBztXaKaiFLFf1iTdUUz_5KugE1lZId17hhnWZ3om0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);